title: 'Alex Escalante'
author:
  name: 'Alejandro Escalante'
description: 'my personal iste'
other:
  home: 'https://alex-esc.github.io/en_us/'
  docs: 'https://alex-esc.github.io/en_us/docs/document_index.html'
  about: 'https://alex-esc.github.io/pages/en_us/about.html'
  language: 'https://alex-esc.github.io/en_us/language.html'

path: 'https://alex-esc.github.io/en_us/'
url:  'https://alex-esc.github.io/en_us/'

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false


plugins:
  - jemoji
  - jekyll-redirect-from
