theme: jekyll-theme-cayman
title: Alejandro Escalante
description: my personal site
show_downloads: true
other:
  home: https://alex-esc.github.io/en_us
  docs: https://alex-esc.github.io/en_us/docs/document_index.html
  about: https://alex-esc.github.io/en_us/pages/about.html
  language: https://alex-esc.github.io/language.html
plugins:
  - jemoji

